tasks/urls.py
from django.urls import path

from tasks.views import (
    IndexView,
    TagsListView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagTaskListView,
    TagsCreateView,
    TagUpdateView,
    TagDeleteView,
)

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("tags/", TagsListView.as_view(), name="tags"),
    path("tags/create/", TagsCreateView.as_view(), name="tags-create"),
    path(
        "tags/<int:pk>/update",
        TagUpdateView.as_view(),
        name="tags-update",
    ),
    path(
        "tags/<int:pk>/delete",
        TagDeleteView.as_view(),
        name="tags-delete",
    ),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path(
        "tasks/<int:pk>/update",
        TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "tasks/<int:pk>/delete",
        TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path(
        "tasks/<int:pk>/add/",
        TagTaskListView.as_view(),
        name="task-update-tag"
    ),
]

app_name = "tasks"

todo_list/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tasks.urls"))
]

tasks/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=63)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.CharField(max_length=100)
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_complete = models.BooleanField()
    tag = models.ManyToManyField(
        Tag,
        related_name="tasks",
    )

    class Meta:
        ordering = ["is_complete", "-datetime"]

    def __str__(self):
        return self.content

tasks/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import generic

from tasks.models import Task, Tag


class IndexView(generic.ListView):
    model = Task
    queryset = Task.objects.all().prefetch_related("tag")
    template_name = "tasks/index.html"


class TagsListView(generic.ListView):
    model = Tag


class TagsCreateView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tags")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("tasks:tags")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("tasks:tags")
    template_name = "tasks/tag_delete.html"


class TaskCreateView(generic.CreateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("tasks:index")


class TaskUpdateView(generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("tasks:index")


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("tasks:index")
    template_name = "tasks/task_delete.html"


class TagTaskListView(generic.ListView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("tasks:index")

    def get(self, request, *args, **kwargs):
        task = get_object_or_404(Task, pk=self.kwargs["pk"])
        task.is_complete = not task.is_complete
        task.save()
        return HttpResponseRedirect(reverse("tasks:index"))

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
        crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <title>Tasks</title>
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-2 ">
        {% block sidebar %}
          {% include "includes/sidebar.html" %}
        {% endblock %}
      </div>
      <div class="col-10">
        {% block content %}


        {% endblock %}
      </div>
    </div>
  </div>
</body>
</html>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  <li><a class="list-item" href="{% url 'tasks:index' %}">Home</a></li>
  <li><a class="list-item" href="{% url 'tasks:tags' %}">Tags</a></li>
</ul>

templates/tasks/index.html
{% extends "base.html" %}

{% block content %}
  <h1>
    TODO List
    <a href="{% url 'tasks:task-create' %}" class="btn btn-primary link-to-page"> Add new task</a>
  </h1>
  {% for task in task_list %}
    <div class="contaner-fluid container-zkh">
      {% if task.is_complete %}
      <div class="container form-group">
        <h3>
          {{ task }}
          <span class="text-success text-uppercase ">Done</span>
        </h3>

        <a href="{% url 'tasks:task-update-tag' pk=task.id %}" class="btn btn-secondary link-to-page"> Undo </a>
        {{ task.datetime }}
      </div>

    {% else %}
      <div class="container">
        <h3>
          {{ task }}
          <span class="text-danger text-uppercase">Not done</span>
        </h3>
        <a href="{% url 'tasks:task-update-tag' pk=task.id %}" class="btn btn-success link-to-page"> Complete</a>
        {{ task.datetime }}
      </div>

      {% if task.deadline %}
        <div class="container text-warning">deadline:  {{ task.deadline }}</div>
      {% endif %}

    {% endif %}
      {% if task.tag %}
        <div class="container">
          {% for tag in task.tag.all %}
          <span class="text-muted">#{{tag }}</span>
          {% endfor %}
        </div>

      {% endif %}
      <div class="container">
        <a href="{% url 'tasks:task-update' pk=task.id %}">Update</a>
        <a href="{% url 'tasks:task-delete' pk=task.id %}" class="link-danger">Delete</a>
      </div>

    </div>
    <br>
    <br>

  {% endfor %}
{% endblock %}

templates/tasks/tag_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/tasks/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}


{% block content%}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>


{% endblock %}

templates/tasks/tag_list.html
{% extends "base.html" %}

{% block content %}

  <h1>
    Tags list
    <a href="{% url 'tasks:tags-create' %}" class="btn btn-primary link-to-page"> Add new tag</a>
  </h1>
  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th></th>
        <th></th>
      </tr>
      {% for tag in tag_list %}
        <tr>
          <td>
            {{ tag }}
          </td>
          <td>
            <a href="{% url 'tasks:tags-update' pk=tag.id %}" class="btn btn-secondary"> Update</a>
          </td>
          <td>
            <a href="{% url 'tasks:tags-delete' pk=tag.id %}" class="btn btn-secondary"> Delete</a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% endif %}
{% endblock %}

templates/tasks/task_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/tasks/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>

{% endblock %}